name 'nodejsapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures nodejsapp'
long_description 'Installs/Configures nodejsapp'
version '0.1.0'
chef_version '>= 14.0'

depends 'nodejs', '~> 6.0.0'
depends 'pm2', '~> 0.7.4'
depends 'nginx', '~> 10.0.2'
