name 'node_sample'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures node_sample'
long_description 'Installs/Configures node_sample'
version '0.1.0'
chef_version '>= 14.0'

depends 'nodejs', '~> 6.0.0'
depends 'apt'
